export const BRAND_COLORS = {
  HOT_PINK: "#FF2E93",
  ACID_LIME: "#C6FF00",
  ELECTRIC_PURPLE: "#7B2FFF",
  BANANA_YELLOW: "#FFE600",
  BLACK: "#000000",
  DARK_BG: "#0a0a0f",
  CARD_SURFACE: "#13131e",
} as const;

export const ROTATING_LOADING_MESSAGES = [
  "CONSULTING THE CAT COUNCIL...",
  "MEASURING YOUR CHAOS...",
  "SNIFFING YOUR VIBES...",
  "CALCULATING PURR-CENTAGE...",
] as const;
